### ISSUE TITLE
Downloading snaps locks account

### ISSUE THREAD

**Issue by mike-burns** [niothiel/snapchat-python#11]
As part of their total lockdown, even downloading snaps using the example script gets an email from them, threatening to lock my account if I do it again.

I bet someone is reverse-engineering this right now, but at least the issue is now raised.

**Comment by DavidBerdik** [comment]
Almost exactly 5 years later, do you know if this still happens?

**Comment by mike-burns** [comment]
I have no idea, sorry! I'll close this since I no longer use Snapchat.
