### ISSUE TITLE
clear_feed() not working

### ISSUE THREAD

**Issue by drewwileyroberts** [niothiel/snapchat-python#12]
The clear_feed() method is returning true, but is not actually clearly.  The number of snaps that it returns in get_snaps() grows each time new ones arrive, only adding new id's to the list and not removing old ones, despite calling clear_feed(). Maybe I am misunderstanding what this function does, or it could be not currently working. Not sure.

**Comment by Amnesthesia** [comment]
+1

This is kind of annoying, as the feed only grows bigger and bigger and fetching snaps gets slower and slower since it goes through all the viewed snaps again, and fail.
