### ISSUE TITLE
I'd like to develop a lib that works with the current version of snapchat.

### ISSUE THREAD

**Issue by Snowlav** [niothiel/snapchat-python#13]
I want to create a new libary to use with the newest version of snapchat, currently 9.2.1.0.
This includes all the new endpoints and a way to avoid detection.

I have both the newest endpoints and the means needed to avoid detection.

Would you like to work with me on this? Please leave a message below with your skype ID.

**Comment by Amnesthesia** [comment]
Can't you just fork this and update the endpoints, user agent and so on? No need to create a completely new lib :o 

What's the new endpoints anyway?

**Comment by niothiel** [comment]
Yup, fork it and I'd be happy to maintain / work with you on it.

**Comment by pgirikishore** [comment]
Is this project still being maintained? If yes, I would like to contribute.

**Comment by vkomarov-r7** [comment]
@pgirikishore: No, this project is no longer maintained.
