### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by pearsonkyle** [niothiel/snapchat-python#14]
When I try to get my snaps it returns false. Or even if I try to upload an image I get a media_id = False.

**Comment by koushag** [comment]
Also getting this issue.

**Comment by PostoAllTheDay** [comment]
Me too !!!

**Comment by benjaminreeve** [comment]
It doesn't work for me either.  It sounds like snap-chat intentionally changed their code base to break the api this is built on.
