### ISSUE TITLE
Error: if 'auth_token' in result: TypeError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by celoufran** [niothiel/snapchat-python#15]
Hi there, I've tried running the example.py script to see if it worked but it's giving me this error:
```
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    s.login(username, password)
  File "C:\Users\<USER>\<FOLDER>\snapchat-python-master\src\snapchat.py", line 199, in login
    if 'auth_token' in result:
TypeError: argument of type 'bool' is not iterable
```

I've also seen that in the post function, the request gives me a 404 response, which automatically returns `False` to the variable `result`. I've also checked what the error is and here's what my debugging comes to so far:

```
Enter your username: <USERNAME>
Enter your password:

Post returned code: 404 for request /login {'username': '<USERNAME>', 'timestamp': 1629330618966L, 'password': '<PASSWORD>', 'version': '4.0.0', 'req_token': '930a2650609124286ee5d1eaf1a1e1f4e9e84d8e1900fa8479b4d314d3c512eb'}

Error content:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Not Found</h1>
</body></html>

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    s.login(username, password)
  File "C:\Users\<USER>\<FOLDER>\snapchat-python-master\src\snapchat.py", line 199, in login
    if 'auth_token' in result:
TypeError: argument of type 'bool' is not iterable
```

What can I do from here?

Thank you!

**Comment by FATCAT47** [comment]
This is the end of the road. I hit this wall and 0 progress from here

**Comment by celoufran** [comment]
Yeah, I've tried reversing the new version of the snapchat app to find the right keys, etc but damn they're not using the KeyStore anymore, or at least if they are they're doing a darn good job at hiding it. I'm pretty sure this is the end of this repo as well. At least I tried a little bit haha!
