### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by akuma-your-death** [niothiel/snapchat-python#18]
im using windows 11 and if i open snapchat.py or example.py im getting:
  File "C:\Users\Downloads\snapchat-python-master\snapchat-python-master\src\snapchat.py", line 170
    print 'Post returned code: ', r.status_code, 'for request', endpoint, data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by vkomarov-r7** [comment]
This project is no longer maintained. That looks like a Python2 vs Python3 error.
